/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pele;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public final class AplikasiPerpustakaan extends javax.swing.JFrame {
    private final DefaultTableModel tableModel;
     //////////////////
    // smangat cukkkk //
    // - pele         //
     //////////////////
    
    /**
     * Creates new form AplikasiPerpustakaan
     */
    public AplikasiPerpustakaan() {
        initComponents();
        String [] judul = {"NIM", "Nama", "Jenis Kelamin", "Fakultas", "Tanggal Pinjam", "Judul Buku", "Pengarang", "Tanggal Kembali"};
        tableModel = new DefaultTableModel(judul, 0);
        tabelMahasiswa.setModel(tableModel);
        showMahasiswa();
    }
    
    public Connection getConnection(){
        Connection connection = null;
        try {
            String url = "jdbc:mysql://localhost:3306/coba";
            String user = "root";
            String pass = "";
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            connection = DriverManager.getConnection(url, user, pass);

        } catch (SQLException e) {
            System.out.println("Ada error dengan pesan: " + e.getMessage());
        }
        return connection;
    }
    
    public void showMahasiswa(){
        int row= tabelMahasiswa.getRowCount();
        for (int i = 0; i < row; i++) {
            tableModel.removeRow(0);
        }
        try {
            String sql = "SELECT * FROM MAHASISWA";
            Connection conn = getConnection();
            ResultSet res = conn.createStatement().executeQuery(sql);
            while(res.next()){
                tableModel.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getDate(5),res.getString(6),res.getString(7),res.getDate(8)});
            }
            tabelMahasiswa.setModel(tableModel);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi gagal pada show mahasiswa");
        }
    }

    public void resetForm(){
        txtNim.setText(null);
        txtNama.setText(null);
        cbFakultas.setSelectedIndex(0);
        cbKelamin.setSelectedIndex(0);
        dcTglKembali.setDate(null);
        dcTglPinjam.setDate(null);
        txtJudul.setText(null);
        txtPengarang.setText(null);
        showMahasiswa();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtPengarang = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        cbKelamin = new javax.swing.JComboBox<>();
        dcTglPinjam = new com.toedter.calendar.JDateChooser();
        cbFakultas = new javax.swing.JComboBox<>();
        dcTglKembali = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        txtCari1 = new javax.swing.JTextField();
        txtCari2 = new javax.swing.JTextField();
        btnCari1 = new javax.swing.JButton();
        btnCari2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("NIM");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nama");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Jenis Kelamin");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Fakultas");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tanggal Pinjam");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Judul");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Tanggal Kembali");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Pengarang");

        txtNim.setBackground(new java.awt.Color(255, 255, 255));

        txtNama.setBackground(new java.awt.Color(255, 255, 255));

        txtPengarang.setBackground(new java.awt.Color(255, 255, 255));

        txtJudul.setBackground(new java.awt.Color(255, 255, 255));

        cbKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        dcTglPinjam.setDateFormatString("yyyy-MM-dd");

        cbFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FTI", "FEB", "FH", "FKIP", "FBS" }));

        dcTglKembali.setDateFormatString("yyyy-MM-dd");

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMahasiswa);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        txtCari1.setBackground(new java.awt.Color(255, 255, 255));
        txtCari1.setForeground(new java.awt.Color(51, 51, 51));

        txtCari2.setBackground(new java.awt.Color(255, 255, 255));
        txtCari2.setForeground(new java.awt.Color(51, 51, 51));

        btnCari1.setText("Cari");
        btnCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari1ActionPerformed(evt);
            }
        });

        btnCari2.setText("Cari");
        btnCari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCari2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama)
                            .addComponent(txtJudul)
                            .addComponent(txtPengarang)
                            .addComponent(dcTglPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcTglKembali, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(cbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNim)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCari2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(txtCari1))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCari1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCari2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnKeluar)))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(dcTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dcTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(txtCari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        int nim = Integer.parseInt(txtNim.getText());
        String nama = txtNama.getText();
        String kelamin = cbKelamin.getSelectedItem().toString();
        String fakultas = cbFakultas.getSelectedItem().toString();
        long tglPinjam = dcTglPinjam.getDate().getTime();
        long tglKembali = dcTglKembali.getDate().getTime();
        String judul = txtJudul.getText();
        String pengarang = txtPengarang.getText();
        
        java.sql.Date tglpinjam = new java.sql.Date(tglPinjam);
        java.sql.Date tglkembali = new java.sql.Date(tglKembali);
        try {
            Connection conn = getConnection();
            conn.createStatement().executeUpdate("INSERT INTO MAHASISWA VALUES ('"+nim+"','"+nama+"','"+kelamin+"','"+fakultas+"','"+tglpinjam+"','"+judul+"','"+pengarang+"','"+tglkembali+"')");
        } catch (SQLException e) {
            System.out.println("Ada error di saveMahasiswa dengan pesan: " + e.getMessage());
        }
        showMahasiswa();
        resetForm();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int nim = Integer.parseInt(txtNim.getText());
        String nama = txtNama.getText();
        String kelamin = cbKelamin.getSelectedItem().toString();
        String fakultas = cbFakultas.getSelectedItem().toString();
        long tglPinjam = dcTglPinjam.getDate().getTime();
        long tglKembali = dcTglKembali.getDate().getTime();
        String judul = txtJudul.getText();
        String pengarang = txtPengarang.getText();
        
        java.sql.Date tglpinjam = new java.sql.Date(tglPinjam);
        java.sql.Date tglkembali = new java.sql.Date(tglKembali);
        try {
            Connection conn = getConnection();
            conn.createStatement().executeUpdate("UPDATE MAHASISWA SET NAMA='"+nama+"',KELAMIN='"+kelamin+"',FAKULTAS='"+fakultas+"',TGL_PINJAM='"+tglpinjam+"',JUDUL='"+judul+"',PENGARANG='"+pengarang+"',TGL_KEMBALI='"+tglkembali+"' WHERE NIM='"+nim+"'");
        } catch (SQLException e) {
            System.out.println("Ada error di updateMahasiswa dengan pesan: " + e.getMessage());
        }
        showMahasiswa();
        resetForm();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int nim = Integer.parseInt(txtNim.getText());
        
        try {
            Connection conn = getConnection();
            conn.createStatement().executeUpdate("DELETE FROM MAHASISWA WHERE NIM='"+nim+"'");
        } catch (SQLException e) {
            System.out.println("Ada error di updateMahasiswa dengan pesan: " + e.getMessage());
        }
        showMahasiswa();
        resetForm();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        
        int row = tabelMahasiswa.getSelectedRow();
        
        txtNim.setText(tabelMahasiswa.getValueAt(row, 0).toString());
        txtNama.setText(tabelMahasiswa.getValueAt(row, 1).toString());
        cbFakultas.setSelectedItem(tabelMahasiswa.getValueAt(row, 2));
        cbKelamin.setSelectedItem(tabelMahasiswa.getValueAt(row, 3));
        dcTglKembali.setDate((Date) tabelMahasiswa.getValueAt(row, 4));
        txtJudul.setText(tabelMahasiswa.getValueAt(row, 5).toString());
        txtPengarang.setText(tabelMahasiswa.getValueAt(row, 6).toString());
        dcTglPinjam.setDate((Date) tabelMahasiswa.getValueAt(row, 7));
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari1ActionPerformed
        // TODO add your handling code here:
        String key = txtCari1.getText();
        int row= tabelMahasiswa.getRowCount();
        for (int i = 0; i < row; i++) {
            tableModel.removeRow(0);
        }
        try {
            String sql = "SELECT * FROM MAHASISWA WHERE FAKULTAS='"+key+"'";
            Connection conn = getConnection();
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery(sql);
            if(res.next()){
                tableModel.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getDate(5),res.getString(6),res.getString(7),res.getDate(8)});
            }
            tabelMahasiswa.setModel(tableModel);
            txtCari1.setText(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi gagal pada show mahasiswa");
        }
    }//GEN-LAST:event_btnCari1ActionPerformed

    private void btnCari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCari2ActionPerformed
        // TODO add your handling code here:
        String key = txtCari2.getText();
        int row= tabelMahasiswa.getRowCount();
        for (int i = 0; i < row; i++) {
            tableModel.removeRow(0);
        }
        try {
            String sql = "SELECT * FROM MAHASISWA WHERE FAKULTAS='"+key+"' OR KELAMIN='"+key+"'";
            Connection conn = getConnection();
            Statement stmt = conn.createStatement();
            ResultSet res = stmt.executeQuery(sql);
            if(res.next()){
                tableModel.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getDate(5),res.getString(6),res.getString(7),res.getDate(8)});
            }
            tabelMahasiswa.setModel(tableModel);
            txtCari2.setText(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi gagal pada show mahasiswa");
        }
    }//GEN-LAST:event_btnCari2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerpustakaan().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari1;
    private javax.swing.JButton btnCari2;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbFakultas;
    private javax.swing.JComboBox<String> cbKelamin;
    private com.toedter.calendar.JDateChooser dcTglKembali;
    private com.toedter.calendar.JDateChooser dcTglPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JTextField txtCari1;
    private javax.swing.JTextField txtCari2;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtPengarang;
    // End of variables declaration//GEN-END:variables
}
